(()=>{"use strict";
const D=[
["PDI / General RV","You're handed an unfamiliar travel trailer for a PDI with no prior notes. Talk me through how you approach it so defects don't get missed.",["I would mostly operate the obvious items and report anything that does not work.","I use a repeatable system-by-system routine, verify operation under normal loads, inspect safety items/fit-finish, document defects and retest repairs.","I start with cosmetic items and let the customer find operational issues later."],1],
["Electrical","A 12V appliance works until it is loaded, then drops out. What are you checking and why?",["Replace the appliance because it fails under load.","Verify source voltage, then measure at the appliance while loaded and work back through connections/grounds to isolate voltage drop; verify repair under load.","Check resistance on the live circuit until I find the bad part."],1],
["LP / Propane","An LP appliance is intermittent and another appliance also seems weak. How do you decide whether this is an appliance problem or an LP supply problem?",["Start replacing the appliance gas valve.","Verify supply with a manometer, including operating/running pressure with demand, inspect regulator/piping and leak-test disturbed connections before condemning the appliance.","If there is propane in the cylinders, LP supply is proven."],1],
["Appliances","A furnace blower runs but you get no heat. Walk me through what has to happen before you condemn a component.",["Replace the board because the blower works.","Verify voltage under load and airflow, follow the sequence through proving/ignition/gas/flame sense, and test the point where the sequence stops.","Replace the sail switch first because it commonly fails."],1],
["Plumbing","A customer reports a water leak but cannot tell you whether it happens on pump or city water. How do you narrow it down?",["Pressurize it and look for water.","Separate pressure sources, inspect/verify pump, city inlet/check valves, fixtures/lines/tanks as applicable, reproduce the condition and verify the repair without exceeding safe test pressure.","Use shop air at full compressor pressure because leaks show faster."],1],
["Slide Outs","One side of a slide moves and the other doesn't. The motor can be heard. What determines your next move?",["Keep running the switch until it catches up.","Identify the slide system, inspect mechanical drive/synchronization/binding and electrical load/control information, use the manufacturer's safe override/bypass only when appropriate, and support the room before invasive work.","Replace the motor because it is making noise."],1],
["Leveling","A leveling system faults partway through operation. What do you prove before replacing a jack or controller?",["Replace the jack that did not move.","Verify voltage/grounds, fluid or mechanical condition as applicable, read/reset faults correctly, verify sensors/zero point and command/output before condemning a component.","Keep clearing the code until the system finishes."],1],
["Brakes / Suspension / Towing","You have a towable with uneven tire wear and a brake complaint. How do you approach it before recommending parts?",["Adjust the brakes and send it.","Safely lift/support as required, inspect bearings/brakes/suspension/tires and wiring, verify adjustment and controller/braking operation, and consider loading/alignment evidence before deciding the cause.","Replace all tires first and see whether the wear returns."],1],
["Inverters","Some inverter-fed receptacles are dead on shore power but work from battery. What are you trying to prove?",["The batteries are bad.","Verify AC input, inverter pass-through/transfer behavior, settings/remote status and output, then isolate upstream/downstream distribution before condemning the inverter.","Replace the inverter because the outlets are on its circuit."],1],
["Generators","A generator starts and runs but the coach has no usable AC power. Walk me through the split between engine-side and electrical-side diagnosis.",["Tune the carburetor because it runs.","Verify generator output voltage/frequency and protection, then transfer/distribution; distinguish an engine/fuel/safety-shutdown issue from rotor/stator/output or coach-side transfer faults.","Replace the transfer switch without checking generator output."],1],
["Solar","A customer wants more solar because the batteries keep going dead. What information do you need before sizing or adding panels?",["Add the largest panel that fits.","Establish loads/energy use, battery capacity/chemistry, existing array/controller ratings, available roof/installation constraints and charging goals before sizing panels/controller/wiring.","Solar panel watts should match battery amp-hours one-for-one."],1],
["Hydraulics","A hydraulic room creeps after being extended. How do you separate a cylinder problem from valve/control or external leakage?",["Replace the cylinder because it is moving.","Inspect for external leaks, verify fluid/lines/fittings and control/solenoid state, use appropriate isolation/bypass testing to distinguish internal cylinder bypass from valve leakage, then verify repair safely.","Tighten the relief valve until it stops creeping."],1],
["Awnings","You need to replace an awning component on a spring-loaded assembly. What has to be established before disassembly?",["Remove the arm and see how much spring tension it has.","Identify the awning/component and spring configuration, secure/support the assembly, control stored spring energy using the correct procedure, then set/verify tension and operation.","Run the awning out fully so the spring has no stored energy."],1],
["Audio / Video","A customer says the TV works on antenna but not satellite. How do you diagnose the coach before blaming the provider?",["Replace the TV input board.","Confirm customer expectation/provider activation, select correct inputs/settings, trace routing through splitters/diplexers/matrix equipment and verify cabling/power/signal path before condemning components.","Satellite and antenna use the same signal, so the TV is bad."],1],
["Interior / Cabinetry","A cabinet is pulling away from a wall and the customer wants it screwed back up. What determines whether that's an acceptable repair?",["Use longer screws anywhere they grab.","Determine structure/backer location and damage, loading and attachment method; repair/support structure as needed, select proper fasteners, protect finish/alignment and verify the component is secure.","Add screws until it stops moving."],1],
["Exterior / Structural","You find water damage behind an exterior component. What do you establish before writing the repair?",["Replace the visibly damaged panel only.","Find and stop the intrusion source, determine extent and structural/material damage, plan component/membrane/metal/fiberglass removal and reinstallation, account for adhesives/sealants and write the repair to restore structure and weather seal.","Seal over the outside and wait to see if the wall dries."],1],
["Sealants","You're resealing a roof component and the old sealant is contaminated and partly painted. What controls your material and prep choice?",["Use self-leveling sealant over everything.","Identify substrates/existing material and compatibility, remove/prep without damaging finishes, use safe cleaners/solvents, choose self-leveling/non-sag as appropriate and apply to a clean compatible surface.","Use the strongest solvent available so nothing remains."],1],
["Flooring","A sheet-vinyl floor needs a localized patch in a patterned area. What makes the difference between an acceptable patch and one that looks repaired?",["Cut a square patch the size of the damage.","Plan around pattern repeat and seam placement, obtain enough material for alignment, prep the substrate, make controlled cuts/seams, use compatible adhesive and roll/finish the repair so pattern and surface lie correctly.","Overlap a patch and glue the edges down."],1],
["Welding","Before welding a bracket on or near an RV chassis, what are your setup and safety considerations?",["Turn the welder up until it penetrates.","Identify material/joint/load, prepare and fit it, select process/settings/consumable, protect the RV from heat/fire/electrical damage, place grounds appropriately, use PPE and inspect the finished weld.","Disconnect shore power; nothing else on the RV is affected by welding."],1],
["Final Skills / Service","You finish a repair that required diagnosis and parts replacement. What does a complete closeout look like before the unit leaves your hands?",["If the failed part is replaced, the job is done.","Recreate/verify the original complaint is corrected, test related operation and safety, check for collateral issues, document cause/correction/test results and leave the unit ready for the next process/customer.","Clear the code and close the job if it does not return immediately."],1]
];
const ADV={
"Electrical":["A coach intermittently trips a GFCI after a downstream receptacle was replaced. What specific wiring or leakage conditions are you trying to prove before replacing the GFCI?",["Replace the GFCI because nuisance trips mean it is weak.","Verify LINE/LOAD placement, neutral-ground isolation downstream, moisture/leakage and branch wiring/load faults; isolate downstream sections and test before condemning the device.","Move the downstream neutral to ground so the GFCI sees less imbalance."],1],
"LP / Propane":["Static LP pressure looks normal, but pressure falls when multiple appliances fire. What does that tell you and what do you test next?",["The regulator is definitely good because static pressure passed.","The fault appears under demand; verify running pressure, regulator capacity/lockup as relevant, cylinder vaporization/supply, restrictions and total appliance demand before isolating the regulator or piping.","Increase regulator pressure until the appliances stay lit."],1],
"Appliances":["A furnace reaches ignition, lights briefly, then drops the flame while the blower continues. What evidence separates flame-proving, LP supply and board/output faults?",["Replace the board.","Observe sequence and flame, verify running LP pressure and flame-sense path/ground/electrode as applicable, then verify board inputs/outputs before condemning it.","Replace the gas valve because flame dropout is always low gas."],1],
"Plumbing":["A water system passes on pump but leaks only on city water. What does that narrow for you?",["The pump is leaking internally.","It points toward components/pressures unique to city-water operation or a pressure-dependent leak; verify regulated city pressure, inlet/check-valve path and reproduce/inspect under that source.","Raise city pressure to make the leak easier to see."],1],
"Slide Outs":["An in-wall slide repeatedly gets out of synchronization but no obvious obstruction is present. What evidence do you want before deciding between adjustment, controller/motor issue, or structural drag?",["Replace both motors.","Compare side-to-side movement/current or controller information as available, inspect room geometry/rollers/seals/structure and wiring, perform correct synchronization procedure, then see whether the fault returns.","Adjust the fastest side until both sides look even."],1],
"Hydraulics":["A hydraulic cylinder will extend under load but drifts back with no external leak. How would an isolation test change your diagnosis?",["It cannot; drift always means cylinder seals.","Properly isolating the cylinder/line can distinguish internal cylinder bypass from valve/manifold leakage; test safely with load supported and interpret whether drift persists.","Cap any line while loaded and see what happens."],1],
"Solar":["A 400W array is being added to an existing controller and lithium bank. What calculations/checks determine whether the controller and wiring can stay?",["Only panel wattage matters.","Check array Voc/Isc for series/parallel configuration against controller input limits, expected charge current/output rating, wire ampacity/drop, battery/BMS charge limits and environmental voltage margin.","If controller is labeled 400W, any 400W array is compatible."],1],
"Generators":["Generator voltage is close to normal unloaded but frequency and voltage sag badly under load. Where does that send the diagnosis?",["Directly to the transfer switch.","Verify engine speed/governor/fuel delivery and load, frequency, voltage regulation/output condition and connections; sag under generator load can be engine-side or generation-side before coach transfer is blamed.","Adjust output voltage only; frequency does not matter to RV loads."],1],
"Brakes / Suspension / Towing":["A trailer pulls under braking but magnet current is present at all wheels. What does that prove—and what doesn't it prove?",["It proves all brakes are working equally.","It proves current path exists, not equal mechanical braking. Inspect/measure adjustment, magnets/drums/shoes/bearings, voltage/current balance and suspension/tire/loading factors.","Increase controller gain until the pull disappears."],1],
"Final Skills / Service":["Your repair works in the bay, but the original complaint occurred only after an hour of travel. What do you document and verify before calling it fixed?",["Bay operation is enough.","Match verification to the original failure conditions as closely as practical, document what was reproduced/tested and any limitations, and avoid claiming a fix that was not meaningfully verified.","Clear codes and state could not duplicate."],1]
};
let st=null,app=document.getElementById("app");
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function save(){localStorage.setItem("tecAdaptive",JSON.stringify(st))}
function start(){let n=document.getElementById("n").value.trim();if(!n)return;st={name:n,loc:document.getElementById("l").value.trim(),exp:document.getElementById("e").value.trim(),di:0,stage:"open",answers:[],scores:{},depth:{}};save();render()}
function opening(){let d=D[st.di];app.innerHTML='<div class="muted">Area '+(st.di+1)+' of '+D.length+'</div><div class="progress"><div class="bar" style="width:'+Math.round(st.di/D.length*100)+'%"></div></div><h2>'+esc(d[0])+'</h2><p>'+esc(d[1])+'</p><textarea id="free" placeholder="Answer the way you would explain it in the shop."></textarea><button id="go">Continue</button><p class="muted">Your written answer is retained as evidence. The next question checks how far to continue in this area.</p>';document.getElementById("go").onclick=()=>{let v=document.getElementById("free").value.trim();if(!v)return;st.answers.push({domain:d[0],type:"free",q:d[1],a:v});st.stage="check";save();render()}}
function check(){let d=D[st.di];app.innerHTML='<h2>'+esc(d[0])+'</h2><p>One quick check before I decide whether to go deeper:</p><h3>'+esc(d[1])+'</h3>'+d[2].map((x,i)=>'<button class="choice" data-i="'+i+'">'+esc(x)+'</button>').join('');document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{let i=+b.dataset.i,ok=i===d[3];st.answers.push({domain:d[0],type:"check",q:d[1],a:d[2][i],correct:ok});st.scores[d[0]]=ok?1:0;if(ok&&ADV[d[0]])st.stage="advanced";else next();save();render()})}
function advanced(){let dom=D[st.di][0],a=ADV[dom];app.innerHTML='<h2>'+esc(dom)+' — deeper diagnostic check</h2><p>'+esc(a[0])+'</p>'+a[1].map((x,i)=>'<button class="choice" data-i="'+i+'">'+esc(x)+'</button>').join('');document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{let i=+b.dataset.i,ok=i===a[2];st.answers.push({domain:dom,type:"advanced",q:a[0],a:a[1][i],correct:ok});st.depth[dom]=ok?2:1;next();save();render()})}
function next(){st.di++;st.stage="open";if(st.di>=D.length)st.stage="done"}
function decisions(){return (window.COURSES||[]).map(c=>{let sc=st.scores[c.domain]||0,dep=st.depth[c.domain]||sc;let high=/advanced|installation|fabrication|certification|sizing|stacked|removal|replacement|fullwire|full wire|residential|basement|spin welding|codes|matrix|freeze damage|bonded structure/i.test(c.title);let sign=sc&&(!high||dep>1);let ev=st.answers.filter(a=>a.domain===c.domain);return{...c,decision:sign?"SIGN":"DON'T SIGN",evidence:sign?(high?"Passed foundational and deeper diagnostic checks; written response retained for audit.":"Passed the domain competency check; written response retained for audit."):(sc?"Foundational evidence present, but deeper evidence was not established for this course.":"Domain check did not establish enough competency for signoff.")}})}
function done(){let r=decisions(),s=r.filter(x=>x.decision==="SIGN").length;app.innerHTML='<h2>'+esc(st.name)+' — placement results</h2><div class="kpis"><div class="kpi"><b>'+s+'</b>SIGN</div><div class="kpi"><b>'+(r.length-s)+'</b>DON\'T SIGN</div><div class="kpi"><b>'+st.answers.length+'</b>Evidence responses</div></div><p>The automated result is a placement recommendation. The complete written-answer transcript is included in the emailed/downloaded audit file.</p><button id="mail">Email results</button><button id="dl">Download audit CSV</button><button class="secondary" id="new">New technician</button><table><thead><tr><th>Course</th><th>Title</th><th>Decision</th><th>Reason</th></tr></thead><tbody>'+r.map(x=>'<tr><td>'+x.code+'</td><td>'+esc(x.title)+'</td><td><b>'+x.decision+'</b></td><td>'+esc(x.evidence)+'</td></tr>').join('')+'</tbody></table>';document.getElementById("new").onclick=()=>{localStorage.removeItem("tecAdaptive");st=null;render()};document.getElementById("dl").onclick=()=>download(r);document.getElementById("mail").onclick=()=>mail(r)}
function auditText(r){let lines=["Bish's RV TEC Placement Assessment",st.name+(st.loc?" — "+st.loc:""),"Experience: "+st.exp,"","RESULTS"];r.forEach(x=>lines.push(x.code+" | "+x.title+" | "+x.decision+" | "+x.evidence));lines.push("","TRANSCRIPT");st.answers.forEach((x,i)=>lines.push((i+1)+". ["+x.domain+"] "+x.q+"\nANSWER: "+x.a+(x.type!=="free"?"\nBRANCH CHECK: "+(x.correct?"PASS":"STOP/LOWER DEPTH"):"")));return lines.join("\n")}
function mail(r){let t=auditText(r),body=t.length>15000?t.slice(0,14500)+"\n\n[Email body shortened. Use audit CSV for complete transcript.]":t;location.href="mailto:?subject="+encodeURIComponent("TEC Placement — "+st.name)+"&body="+encodeURIComponent(body)}
function download(r){let rows=[["Type","Technician","Location","Domain","Course","Title","Decision","Question","Answer","Evidence"]];r.forEach(x=>rows.push(["RESULT",st.name,st.loc,x.domain,x.code,x.title,x.decision,"","",x.evidence]));st.answers.forEach(x=>rows.push(["EVIDENCE",st.name,st.loc,x.domain,"","","",x.q,x.a,x.type==="free"?"Verbatim response":(x.correct?"Branch check passed":"Branch check failed / depth stopped")]));let csv=rows.map(row=>row.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="TEC_Placement_Audit_"+st.name.replace(/\W+/g,"_")+".csv";a.click()}
function render(){if(!st){app.innerHTML='<h2>Start a new technician assessment</h2><label>Technician name<input id="n"></label><label>Location<input id="l"></label><label>Prior experience<textarea id="e" placeholder="RV, automotive, electrical, plumbing, construction, or related experience."></textarea></label><button id="start">Start assessment</button><p class="muted">This assessment adapts depth by skill area. Written answers are preserved for audit; targeted checks determine whether the interview goes deeper or moves on.</p>';document.getElementById("start").onclick=start;return}if(st.stage==="done")done();else if(st.stage==="advanced")advanced();else if(st.stage==="check")check();else opening()}
try{st=JSON.parse(localStorage.getItem("tecAdaptive")||"null")}catch{}render();
})();