const CORE_DOMAINS=['PDI / General RV','LP / Propane','Electrical','Appliances','Plumbing','Slide Outs','Brakes / Suspension / Towing','Sealants'];
const SYN={'volts':'voltage','volt':'voltage','vdc':'voltage','vac':'voltage','amps':'current','amp':'current','amperage':'current','ohms':'resistance','ohm':'resistance','propane':'lp','refer':'refrigerator','fridge':'refrigerator','grounds':'ground','breakers':'breaker','fuses':'fuse','leaks':'leak','wires':'wire','batteries':'battery','controllers':'controller','generators':'generator','slides':'slide','awnings':'awning','hydraulics':'hydraulic'};
let S={name:'',location:'',claimed:new Set(),generalIndex:0,generalScores:[],level:'',domains:[],domainIndex:0,domainPass:{},bundleIndex:0,results:{},evidence:{},answers:[],phase:'profile'};
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(x){return String(x||'').toLowerCase().replace(/[^a-z0-9\s/-]/g,' ').split(/\s+/).filter(Boolean).map(w=>SYN[w]||w).join(' ')}
function score(text,terms){let n=norm(text);let hit=[];for(const t0 of terms){let t=SYN[t0]||t0;if(t&&n.includes(t)&&!hit.includes(t))hit.push(t)}let strong=hit.length>=Math.min(3,Math.max(2,Math.ceil(terms.length*.3))) || (text.trim().length>160&&hit.length>=2);let partial=!strong&&(hit.length>=1||text.trim().length>80);return {strong,partial,hits:hit}}
function app(h){document.getElementById('app').innerHTML=h} function meta(t){document.getElementById('meta').textContent=t} function progress(p){document.getElementById('fill').style.width=Math.max(0,Math.min(100,p))+'%'}
function restart(){S={name:'',location:'',claimed:new Set(),generalIndex:0,generalScores:[],level:'',domains:[],domainIndex:0,domainPass:{},bundleIndex:0,results:{},evidence:{},answers:[],phase:'profile'};document.getElementById('restartTop').style.display='none';profile()}
function profile(){meta('New-hire competency placement');progress(0);app(`<span class="tag">Placement assessment</span><h1>Let's see what you already know.</h1><p>This is not a textbook test. Answer the way you would talk through a job in the shop. The assessment starts broad and only goes deeper where your answers show enough foundation to justify it.</p><div class="grid"><label>Technician name<input id="nm" type="text"></label><label>Location<input id="loc" type="text"></label></div><div class="note">If you do not know something, say so. That simply leaves the related TEC course open for training and validation.</div><div class="actions"><button class="primary" onclick="toClaims()">Continue</button></div>`)}
function toClaims(){S.name=document.getElementById('nm').value.trim()||'Technician';S.location=document.getElementById('loc').value.trim();claims()}
function claims(){let ds=[...new Set(COURSES.map(c=>c.domain))];app(`<span class="tag">Starting point</span><h2>What kinds of work have you actually done?</h2><p>Check the areas you have hands-on experience with. This does <b>not</b> sign anything off. It only helps prioritize follow-up if your general answers support going deeper.</p><div class="checks">${ds.map(d=>`<label class="check"><input type="checkbox" value="${esc(d)}"> <span>${esc(d)}</span></label>`).join('')}</div><div class="actions"><button class="primary" onclick="beginGeneral()">Start</button></div>`)}