function beginGeneral(){document.querySelectorAll('input[type=checkbox]:checked').forEach(x=>S.claimed.add(x.value));S.phase='general';S.generalIndex=0;generalQ()}
function generalQ(){let q=GENERAL[S.generalIndex];if(!q)return endGeneral();meta(`General knowledge • ${S.generalIndex+1} of ${GENERAL.length}`);progress((S.generalIndex/GENERAL.length)*18);app(`<span class="tag">General knowledge</span><div class="prompt">${esc(q.q)}</div><textarea id="ans" placeholder="Talk me through it like you would in the shop..."></textarea><div class="actions"><button class="secondary" onclick="generalUnsure()">I'm not sure</button><button class="primary" onclick="generalSubmit()">Continue</button></div>`)}
function generalUnsure(){S.generalScores.push(0);S.answers.push({id:GENERAL[S.generalIndex].id,text:'I am not sure',score:0});S.generalIndex++;generalQ()}
function generalSubmit(){let t=document.getElementById('ans').value.trim();if(!t)return;let r=score(t,GENERAL[S.generalIndex].terms),v=r.strong?2:r.partial?1:0;S.generalScores.push(v);S.answers.push({id:GENERAL[S.generalIndex].id,text:t,score:v,hits:r.hits});S.generalIndex++;generalQ()}
function endGeneral(){let pts=S.generalScores.reduce((a,b)=>a+b,0),strong=S.generalScores.filter(x=>x===2).length;if(strong<=2||pts<6){S.level='novice';return finalize('General answers reached the current competency ceiling.')}if(strong>=6&&pts>=12)S.level='advanced';else S.level='mid';let all=[...new Set(COURSES.map(c=>c.domain))];S.domains=S.level==='advanced'?all:[...new Set([...CORE_DOMAINS,...S.claimed])];S.domainIndex=0;domainQ()}
function domainQ(){if(S.domainIndex>=S.domains.length)return startBundles();let d=S.domains[S.domainIndex],cfg=DOMAIN_SCREENS[d];meta(`System check • ${S.domainIndex+1} of ${S.domains.length}`);progress(18+(S.domainIndex/Math.max(1,S.domains.length))*22);app(`<span class="tag">${esc(d)}</span><h2>Let's check this area before going deeper.</h2><div class="prompt">${esc(cfg[0])}</div><textarea id="ans" placeholder="Explain your diagnostic or repair approach..."></textarea><div class="actions"><button class="secondary" onclick="domainUnsure()">I'm not sure</button><button class="primary" onclick="domainSubmit()">Continue</button></div>`)}
function domainUnsure(){let d=S.domains[S.domainIndex];S.domainPass[d]=false;S.answers.push({id:'DOMAIN:'+d,text:'I am not sure',score:0});S.domainIndex++;domainQ()}
function domainSubmit(){let d=S.domains[S.domainIndex],t=document.getElementById('ans').value.trim();if(!t)return;let r=score(t,DOMAIN_SCREENS[d][1]);S.domainPass[d]=r.strong;S.answers.push({id:'DOMAIN:'+d,text:t,score:r.strong?2:r.partial?1:0,hits:r.hits});S.domainIndex++;domainQ()}
function startBundles(){let evaluated=new Set(S.domains);for(const c of COURSES){if(!evaluated.has(c.domain)||!S.domainPass[c.domain]){S.results[c.code]='DON\'T SIGN';S.evidence[c.code]=!evaluated.has(c.domain)?'No placement evidence collected at this depth; course remains open.':'Domain screen did not demonstrate enough foundation to justify deeper placement credit.'}}S.bundleDomains=S.domains.filter(d=>S.domainPass[d]);S.bundleDomainIndex=0;S.bundleIndex=0;bundleQ()}
function bundlesFor(d){let a=COURSES.filter(c=>c.domain===d);let out=[];for(let i=0;i<a.length;i+=4)out.push(a.slice(i,i+4));return out}