'use client';import{useState}from'react';
export default function Page(){const[state,setState]=useState(null),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[results,setResults]=useState(null),[error,setError]=useState(''),[name,setName]=useState(''),[location,setLocation]=useState(''),[experience,setExperience]=useState('');
async function call(payload){setBusy(true);setError('');try{const r=await fetch('/api/assess',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');setState(d.state);if(d.question)setQuestion(d.question);if(d.results)setResults(d.results);setAnswer('')}catch(e){setError(e.message)}finally{setBusy(false)}}
function start(){if(!name.trim())return setError('Enter the technician name.');call({action:'start',state:{name:name.trim(),location:location.trim(),experience:experience.trim(),turn:0,currentDomain:null,pendingQuestion:null,history:[],ledger:{},screenedDomains:[],complete:false}})}
function submit(){call({state,answer})}function restart(){setState(null);setQuestion('');setResults(null);setAnswer('');setError('');setName('');setLocation('');setExperience('')}
function csv(){const rows=[['Technician','Location','Course','Title','Decision','Evidence'],...results.map(r=>[state.name,state.location,r.code,r.title,r.decision,r.evidence])],text=rows.map(x=>x.map(v=>'\"'+String(v??'').replaceAll('\"','\"\"')+'\"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='TEC_Placement_'+state.name.replace(/[^a-z0-9]+/gi,'_')+'.csv';a.click()}
function email(){const signed=results.filter(r=>r.decision==='SIGN'),body=`Bish's RV TEC Placement Assessment\n${state.name}${state.location?' — '+state.location:''}\n\nSIGN: ${signed.length}\nDON'T SIGN: ${results.length-signed.length}\n\nCourses recommended for signoff:\n${signed.map(x=>x.code+' — '+x.title).join('\n')||'None'}\n\nComplete evidence report is available from Download CSV.`;location.href='mailto:?subject='+encodeURIComponent('TEC Placement Results — '+state.name)+'&body='+encodeURIComponent(body)}
if(results)return <main><header><h1>Bish's RV TEC Placement Assessment</h1><p>Internal reviewer results — {state.name}</p></header><section className="card"><div className="kpis"><div><b>{results.filter(r=>r.decision==='SIGN').length}</b><span>SIGN</span></div><div><b>{results.filter(r=>r.decision!=='SIGN').length}</b><span>DON'T SIGN</span></div><div><b>{results.length}</b><span>Applicable courses</span></div></div><div className="actions"><button onClick={csv}>Download CSV</button><button onClick={email}>Email results</button><button onClick={restart}>New technician</button></div><table><thead><tr><th>Course</th><th>Title</th><th>Decision</th><th>Evidence</th></tr></thead><tbody>{results.map(r=><tr key={r.code}><td>{r.code}</td><td>{r.title}</td><td><strong>{r.decision}</strong></td><td>{r.evidence}</td></tr>)}</tbody></table></section></main>;
if(!state)return <main><header><h1>Bish's RV TEC Placement Assessment</h1><p>New-hire competency placement</p></header><section className="card"><label>Technician name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Prior experience<textarea value={experience} onChange={e=>setExperience(e.target.value)} placeholder="RV, automotive, electrical, plumbing, construction, or related experience."/></label>{error&&<p className="err">{error}</p>}<button onClick={start} disabled={busy}>{busy?'Starting…':'Start assessment'}</button></section></main>;
return <main><header><h1>Bish's RV TEC Placement Assessment</h1><p>{state.name}{state.location?' — '+state.location:''}</p></header><section className="card"><div className="progress">Conversation {state.turn+1}</div><h2>{question}</h2><textarea className="answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Answer the way you would explain it in the shop." autoFocus/>{error&&<p className="err">{error}</p>}<button onClick={submit} disabled={busy||!answer.trim()}>{busy?'Reviewing your answer…':'Continue'}</button><p className="note">Use normal shop language. The assessment is evaluating what you demonstrate, not whether you use specific textbook words.</p></section></main>}