import {generateText} from 'ai';import {COURSES,DOMAINS,byDomain,GENERAL,finalResults} from '../../../lib/engine';
const ORDER=['PDI / General RV','Final Skills / Service','Electrical','LP / Propane','Appliances','Plumbing','Slide Outs','Leveling','Brakes / Suspension / Towing','Inverters','Generators','Solar','Hydraulics','Awnings','Audio / Video','Interior / Cabinetry','Exterior / Structural','Sealants','Flooring','Welding'];
function json(s){const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<a)throw Error('Evaluator returned invalid output');return JSON.parse(s.slice(a,b+1))}
function nextDomain(s){return ORDER.find(d=>DOMAINS.includes(d)&&!s.screenedDomains.includes(d))||DOMAINS.find(d=>!s.screenedDomains.includes(d))||null}
function candidates(s){if(s.currentDomain)return byDomain(s.currentDomain);return COURSES.filter(c=>['PDI / General RV','Electrical','LP / Propane','Appliances','Plumbing','Final Skills / Service'].includes(c.domain))}
export async function POST(req){try{const b=await req.json(),s=b.state;if(b.action==='start')return Response.json({state:s,question:GENERAL[0]});const answer=(b.answer||'').trim();if(!answer)return Response.json({error:'Answer in your own words before continuing.'},{status:400});const q=s.pendingQuestion||GENERAL[Math.min(s.turn,GENERAL.length-1)];s.history.push({question:q,answer});s.turn++;
const cand=candidates(s).slice(0,40);const prompt=`You are a senior RV technician evaluating a new hire for Bish's RV TEC placement. Reason through the technician's meaning like an experienced trainer. DO NOT keyword-score. Credit correct shop language, shorthand, alternate valid sequences, and tests that demonstrate a concept without naming it. Do not require textbook vocabulary. Do not infer hands-on competency from confidence alone. Safety/procedural skills need explicit evidence. One answer may support multiple courses. A weak answer affects only related competencies, never unrelated courses. Existing evidence may combine across turns.\n\nQUESTION: ${q}\nTECHNICIAN ANSWER: ${answer}\nAREA: ${s.currentDomain||'broad RV screening'}\nCANDIDATE COURSES: ${JSON.stringify(cand)}\nEXISTING LEDGER: ${JSON.stringify(s.ledger)}\n\nReturn ONLY JSON: {"updates":[{"code":123,"decision":"SIGN|OPEN","evidence":"specific evidence in plain language"}],"assessment":"what this answer actually proves","followUpNeeded":true,"followUpQuestion":"one natural targeted trainer question","domainCeilingReached":false}. SIGN only when you would genuinely sign that TEC course from the accumulated evidence. OPEN records useful but insufficient evidence. Ask a follow-up only when it can resolve an important uncertainty. If the technician clearly lacks the foundation in THIS AREA, set domainCeilingReached true instead of dragging them through advanced questions.`;
const out=await generateText({model:process.env.TEC_MODEL||'openai/gpt-5-mini',prompt});const ev=json(out.text);for(const u of ev.updates||[]){const c=COURSES.find(x=>x.code===Number(u.code));if(!c)continue;const k=String(c.code),old=s.ledger[k];if(u.decision==='SIGN'||!old||old.decision!=='SIGN')s.ledger[k]={decision:u.decision==='SIGN'?'SIGN':'OPEN',evidence:u.evidence||ev.assessment||'Evidence recorded.'}}
if(!s.currentDomain&&s.turn<GENERAL.length){s.pendingQuestion=GENERAL[s.turn];return Response.json({state:s,question:s.pendingQuestion,assessment:ev.assessment})}
if(!s.currentDomain){s.currentDomain=nextDomain(s)}
else if(ev.followUpNeeded&&!ev.domainCeilingReached){s.pendingQuestion=ev.followUpQuestion;return Response.json({state:s,question:s.pendingQuestion,assessment:ev.assessment})}
else{if(!s.screenedDomains.includes(s.currentDomain))s.screenedDomains.push(s.currentDomain);s.currentDomain=nextDomain(s)}
if(!s.currentDomain){s.complete=true;return Response.json({state:s,complete:true,results:finalResults(s)})}
s.pendingQuestion=`Let's switch to ${s.currentDomain}. Give me an example of the most involved work you've personally done in this area. Walk me through what you found, what you checked or did, and how you knew the repair or system was right when you were done.`;return Response.json({state:s,question:s.pendingQuestion,assessment:ev.assessment})
}catch(e){return Response.json({error:e.message||'Assessment engine error'},{status:500})}}